name: DiJit-Generation Test and Deployment

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow==2.9.0
          pip install -r requirements.txt
      - name: Launch test main
        run: |
          python test.py

  build-containerized-app:
  
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
      - name: Compute the container version
        id: version
        run: echo "version=$(git describe --tags)" >> "$GITHUB_OUTPUT"
      - name: Build the container
        run: docker build -t "gionceschelli/dijit-generation:${{ steps.version.outputs.version }}" .
      - name: Tag as latest
        run: docker tag "gionceschelli/dijit-generation:${{ steps.version.outputs.version }}" "gionceschelli/dijit-generation:latest"
      - name: Deliver on dockerhub
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          echo ${{ secrets.DOCKER_PSW }} | docker login -u gionceschelli --password-stdin
          docker push gionceschelli/dijit-generation:${{ steps.version.outputs.version }}
          docker push gionceschelli/dijit-generation:latest
